### PR TITLE
Add timestamp support

### PR DESCRIPTION
**Pull request by stefan-hudelmaier**

### CODE REVIEW

**Comment by j-oliver** [comment]
Please try to run prettier if your IDE doesn't do it for you before you check in the files.

**Comment by j-oliver** [comment]
Since this is will result in a breaking change anyway. Shouldn't we also modify `useTelemetry` and `useD2CMessages` too?

From
```ts
const value = useTelemetry('mydevice', 'mytelemetry');
const lastMessage = useD2CMessages('mydevice');
```
to
```ts
const [value, ts] = useTelemetry('mydevice', 'mytelemetry');
const [lastMessage, ts] = useD2CMessages('mydevice');
```

And update the `onData` callback in these hooks aswell?

**Comment by stefan-hudelmaier** [comment]
I would like to keep `useTelemetry` dead simple, so only return the value. `onData` could be extended, however, so if the timestamp is required, this can be used (or `useMultiTelemetry`). For now, I would also leave `useD2CMessage`, although I feel less strongly about it.

**Comment by j-oliver** [comment]
if I `npm install` I get diffs in the version field of the package-lock.json. could you `npm install` and commit again?

**Comment by j-oliver** [comment]
> I would like to keep `useTelemetry` dead simple, so only return the value. `onData` could be extended, however, so if the timestamp is required, this can be used (or `useMultiTelemetry`). For now, I would also leave `useD2CMessage`, although I feel less strongly about it.

Okay that's fine with me, we should however update both `onData` functions.

**Comment by stefan-hudelmaier** [comment]
I have updated `package-lock.json`. Could you adapt the `onData` function? I think you will be faster.

**Pull request merged**
